# Date: 09/11/2020  
# Class: CS4541  
# Assignment: Assignment 0 - Simple C Program  
# Author(s): Darryl Ming Sen Lee 

fileName= simple_c_program

flash:
	gcc -std=c99 -Wall $(fileName).c -o $(fileName)
	./$(fileName)

remove:
	rm $(fileName)
	

