# Date: 09/17/2020  
# Class: CS4541  
# Assignment: Assignment 1 - Number Demonstrations 
# Author(s): Darryl Ming Sen Lee 

fileName= number_demo

all:
	gcc -std=c99 -Wall $(fileName).c -o $(fileName)

run: 
	./$(fileName)

clean:
	rm $(fileName)